/** FETCH PRODUCTS */
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';

/** FILTER PRODUCTS */
export const FILTER_FEATURED_PRODUCTS = 'FILTER_FEATURED_PRODUCTS';
export const FILTER_BY_BEDROOMS = 'FILTER_POSTS_BY_BEDROOMS';
export const FILTER_BY_GUESTS = 'FILTER_POSTS_BY_GUESTS';
export const FILTER_BY_PRODUCT_TYPES = 'FILTER_BY_PRODUCT_TYPES';

/** SEARCH PRODUCTS */
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const SEARCH_PRODUCTS_FAIL = 'SEARCH_PRODUCTS_FAIL';
export const SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS';

/** SELECT PRODUCT */
export const SELECT_PRODUCT = 'SELECT_PRODUCT';

/** FETCH PRODUCT IMAGES */
export const FETCH_PRODUCT_IMAGES = 'FETCH_PRODUCT_IMAGES';

/** LOADING PRODUCTS */
export const LOADING_PRODUCTS = 'LOADING_PRODUCTS';
