export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';

export const FILTER_BY_TAGS = 'FILTER_POSTS_BY_TAGS';
export const FILTER_BY_CATEGORIES = 'FILTER_POSTS_BY_CATEGORIES';

export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';

export const SEARCH_POSTS = 'SEARCH_POSTS';
export const SEARCH_POSTS_FAIL = 'SEARCH_POSTS_FAIL';
export const SEARCH_POSTS_SUCCESS = 'SEARCH_POSTS_SUCCESS';

export const SELECT_POST = 'SELECT_POST';

export const FETCH_POST_IMAGES = 'FETCH_POST_IMAGES';

export const FETCH_RELATED_POSTS = 'FETCH_RELATED_POSTS';
export const LOADING_POSTS = 'LOADING_POSTS';
