export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';

export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';

export const FILTER_BY_TAGS = 'FILTER_POSTS_BY_TAGS';
export const FILTER_BY_CATEGORIES = 'FILTER_POSTS_BY_CATEGORIES';

export const FILTER_BY_BEDROOMS = 'FILTER_POSTS_BY_BEDROOMS';
export const FILTER_BY_GUESTS = 'FILTER_POSTS_BY_GUESTS';
export const FILTER_BY_PRODUCT_TYPES = 'FILTER_BY_PRODUCT_TYPES';

export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';

export const SEARCH_POSTS = 'SEARCH_POSTS';
export const SEARCH_POSTS_FAIL = 'SEARCH_POSTS_FAIL';
export const SEARCH_POSTS_SUCCESS = 'SEARCH_POSTS_SUCCESS';

export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const SEARCH_PRODUCTS_FAIL = 'SEARCH_PRODUCTS_FAIL';
export const SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS';

export const SELECT_POST = 'SELECT_POST';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';

export const FETCH_POST_IMAGES = 'FETCH_POST_IMAGES';
export const FETCH_RELATED_POSTS = 'FETCH_RELATED_POSTS';

export const FETCH_PRODUCT_IMAGES = 'FETCH_PRODUCT_IMAGES';

export const LOADING_POSTS = 'LOADING_POSTS';
export const LOADING_PRODUCTS = 'LOADING_PRODUCTS';
